### ISSUE TITLE
Free all allocated memory and open file/image.

### ISSUE THREAD

**Issue by fluffy-kaiju** [fluffy-willa-42-team/cube3d#11]
```
	//TODO Free all allocated memory and open file/image.
```

https://github.com/fluffy-willa-42-team/cube3d/blob/8a0e5dbd53522655210d9d97edae5ff8f0c964ea/src/0_parser/parser.c#L28

**Comment by fluffy-kaiju** [comment]
# Todo
- [x] free and close parser data #20 
- [x] @willaCS free and close mlx data
- [ ] User delete function from vec_lib

**Comment by fluffy-kaiju** [comment]
Use vec_init function ptr param for the mlx image

remove while loop and put as function
https://github.com/fluffy-willa-42-team/cube3d/blob/41ddb1e3f8524780aa5a021f60fc834b9d5a2486/src/utils/parser/destroy_data.c#L36-L43
