### ISSUE TITLE
Rework C3_DEBUG and add it to cube3d_debug.h

### ISSUE THREAD

**Issue by fluffy-kaiju** [fluffy-willa-42-team/cube3d#2]
https://github.com/fluffy-willa-42-team/cube3d/blob/a0bec7807c1c8588043d2c58e0557c4a05af2cf7/src/0_parser/b_cub_to_cube/cub_map_conv.c#L56-L64

**Comment by fluffy-kaiju** [comment]
## TODO

- [ ] ~~Check if there is no problem with the 42 norm~~
- [ ] Make tree variant of the function
    * [ ] one that return a value to use as argument in `return()` 
    * [ ] another to print custom debug.
    * [ ] one that use `perror()` if we catch error from a function in a std lib

**Comment by fluffy-kaiju** [comment]
Impossible de le faire à la norme pour la macro :/

> Les constantes de préprocesseur (or #define) que vous créez ne doivent être utilisés que pour associer des valeurs littérales et constantes, et rien d’autre.

> Error: Preprocessor statement must only contain constant defines

> Error: Too many values on define
