### ISSUE TITLE
Make new test unit map file

### ISSUE THREAD

**Issue by fluffy-kaiju** [fluffy-willa-42-team/cube3d#22]

**Comment by fluffy-kaiju** [comment]
# Notes

The currents in the test file are outdated.

### todo
cub
- [x] token texture
    - [x] bad token texture
    - [x] duplicate token texture
- [ ] option texture 
    - [ ] bad noclip
    - [ ] bad transparency
    - [ ] good noclip
    - [ ] good transparency
- [ ] bad texture color
- [ ] bad texture file

**Comment by fluffy-kaiju** [comment]
WIP on https://github.com/fluffy-willa-42-team/cube3d/tree/patch_testunit
