### ISSUE TITLE
Create separator between texture part and map for cube format

### ISSUE THREAD

**Issue by fluffy-kaiju** [fluffy-willa-42-team/cube3d#6]
## TODO

- [x] In the cub to cube part, add `~~~` at the end of texture part.
- [x] In the cube tex parser break when the `~~~` sequence is occurred.
- [x] For the cube parser, use the sequence `~` to skip comment line.
https://github.com/fluffy-willa-42-team/cube3d/blob/c55577eb5c6513a54f9751d20347850f37b23226/src/0_parser/c_cube_to_t_map/cube_to_t_map.c#L174-L181

**Comment by fluffy-kaiju** [comment]
Separator sequence for `.cube` format implemented.
